version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cowtrave_db
      POSTGRES_USER: cowuser_db
      POSTGRES_PASSWORD: Romazaloko123.
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cowuser_db:Romazaloko123.@db:5432/cowtrave_db

volumes:
  db-data:
