version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://cowtravel_user:Romazaloko123.@db:3306/mydb
  db:
    image: postgres
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=cowtravel_user
      - MYSQL_PASSWORD=Romazaloko123.
    volumes:
      - db-data:/var/lib/postgres

volumes:
  db-data:
