version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:Romazaloko123.@node_db:27017/mydatabase?authSource=admin&directConnection=true"
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "27017:27017"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Romazaloko123.
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
