version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: francescoxx/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=postgres-cowtravel
      - PG_USER=postgres
      - PG_PASSWORD=Romazaloko123.
      - PG_HOST=95.163.230.74
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres-cowtravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Romazaloko123.
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
