version: "3"
services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
      - react-app
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./cowtravel:/usr/src/app/build
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    ports: -"80:80"

  react-app:
    build: ../cowtravel-react-app
    container_name: react-app

  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: Romazaloko123.
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
