version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - pg_db
    environment:
      - DATABASE_URL=postgresql://root:Romazaloko123.@pg_db:5432/mydb
  pg_db:
    image: postgres
    environment:
      - POSTGRES_HOST=pg_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Romazaloko123.
    volumes:
      - db-data:/var/lib/postgres

volumes:
  db-data:
