version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: Romazaloko123.
  app:
    build: .
    command: npm start
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - react-app
  nginx:
    container_name: cowtravel_nginx
    image: nginx:latest
    ports:
      - "${SSL_PORT}:443"
      - "${HTTP_PORT}:80"
    volumes:
      - /var/www/html
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
  react-app:
    build: ../cowtravel-react-app
    ports:
      - "80:80"
