version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - react-app
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: Romazaloko123.
  react-app:
    build: ../cowtravel-react-app
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
