version: "1"
services:
  express-app: # Сервер Express
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - react-app
    environment:
      DATABASE_URL: "postgresql://postgres:Romazaloko123.@95.163.230.74:5432/postgres"
  db: # База данных
    image: postgres
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: postgres
      MONGO_INITDB_ROOT_PASSWORD: Romazaloko123.
