version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: Romazaloko123.
  app:
    build: .
    command: npm start
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - react-app
  react-app:
    build: ../cowtravel-react-app
    ports:
      - "80:80"
